# Generated by Django 6.0.6 on 2026-06-12 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDireccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTransmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('turbo', models.BooleanField(default=False)),
                ('anio', models.IntegerField()),
                ('nuevo', models.BooleanField(default=True)),
                ('kilometros', models.IntegerField(default=0)),
                ('patente', models.CharField(blank=True, max_length=20, null=True)),
                ('puertas', models.IntegerField(default=4)),
                ('marchas', models.IntegerField(default=5)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='autos/')),
                ('activo', models.BooleanField(default=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.color')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.marca')),
                ('combustible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.tipocombustible')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.tipodireccion')),
                ('transmision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.tipotransmision')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
